# Generated by Django 2.0.7 on 2018-10-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0002_auto_20181002_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='profile_photo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.DecimalField(decimal_places=6, max_digits=6),
        ),
    ]
