# Generated by Django 2.0.7 on 2018-10-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0005_auto_20181002_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='Computer science & Engineering', max_length=20),
            preserve_default=False,
        ),
    ]
