# Generated by Django 2.0.7 on 2018-10-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0006_student_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(max_length=30),
        ),
    ]
