# Generated by Django 2.0.7 on 2018-10-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0007_auto_20181006_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.FileField(upload_to='profile_photo'),
        ),
    ]
